### ISSUE TITLE
debris at the page end

### ISSUE THREAD

**Issue by matkoniecz** [samuelclay/ofbrooklyn#1]
> This is a [four part series]({{ page.url }}) 

is shown at the end of https://github.com/samuelclay/ofbrooklyn/blob/master/_posts/2019-01-03-building-turntouch.markdown

**Comment by matkoniecz** [comment]
hmm, or maybe it is processed further and it is not problem there?

**Comment by samuelclay** [comment]
Thanks for noticing that but you are correct in that it is later processed. I use Jekyll and you can see in the screenshot from the blog post that it is working as intended.

https://www.ofbrooklyn.com/2019/01/3/building-turntouch/

<img width="833" alt="Screen Shot 2021-03-01 at Mar 1 5 44 39 PM" src="https://user-images.githubusercontent.com/44229/109569091-e1268780-7ab5-11eb-9a24-2881b0530ced.png">
